/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductCategory = IDL.Variant({
  'clothing' : IDL.Null,
  'accessories' : IDL.Null,
  'bags' : IDL.Null,
  'customOrders' : IDL.Null,
});
export const NewProduct = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'sizes' : IDL.Vec(IDL.Text),
  'stock' : IDL.Nat,
  'category' : ProductCategory,
  'colors' : IDL.Vec(IDL.Text),
  'priceCents' : IDL.Nat,
  'images' : IDL.Vec(IDL.Text),
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'sizes' : IDL.Vec(IDL.Text),
  'stock' : IDL.Nat,
  'category' : ProductCategory,
  'colors' : IDL.Vec(IDL.Text),
  'priceCents' : IDL.Nat,
  'images' : IDL.Vec(IDL.Text),
});
export const Time = IDL.Int;
export const ContactMessage = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const Review = IDL.Record({
  'content' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'productId' : IDL.Opt(IDL.Nat),
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func([NewProduct], [IDL.Nat], []),
  'addReview' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Nat), IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'findProductByName' : IDL.Func([IDL.Text], [Product], ['query']),
  'getContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getProductReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByPrice' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'seedData' : IDL.Func([], [], []),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'subscribeEmail' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductCategory = IDL.Variant({
    'clothing' : IDL.Null,
    'accessories' : IDL.Null,
    'bags' : IDL.Null,
    'customOrders' : IDL.Null,
  });
  const NewProduct = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'sizes' : IDL.Vec(IDL.Text),
    'stock' : IDL.Nat,
    'category' : ProductCategory,
    'colors' : IDL.Vec(IDL.Text),
    'priceCents' : IDL.Nat,
    'images' : IDL.Vec(IDL.Text),
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'sizes' : IDL.Vec(IDL.Text),
    'stock' : IDL.Nat,
    'category' : ProductCategory,
    'colors' : IDL.Vec(IDL.Text),
    'priceCents' : IDL.Nat,
    'images' : IDL.Vec(IDL.Text),
  });
  const Time = IDL.Int;
  const ContactMessage = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const Review = IDL.Record({
    'content' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'productId' : IDL.Opt(IDL.Nat),
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func([NewProduct], [IDL.Nat], []),
    'addReview' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat), IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'findProductByName' : IDL.Func([IDL.Text], [Product], ['query']),
    'getContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
    'getProductReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByPrice' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'seedData' : IDL.Func([], [], []),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'subscribeEmail' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };